# Generated by Django 5.2.16 on 2026-07-19 12:57

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_employeeprofile_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="attachment",
            field=models.FileField(
                blank=True,
                upload_to="chat_uploads/",
                validators=[apps.core.validators.validate_chat_attachment],
            ),
        ),
        migrations.AlterField(
            model_name="medicalrecord",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to="reports/",
                validators=[apps.core.validators.validate_medical_document],
            ),
        ),
    ]
