# Generated by Django 5.2.16 on 2026-07-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_chatmessage_attachment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="mode",
            field=models.CharField(
                choices=[
                    ("clinic", "In-clinic"),
                    ("video", "Video consultation (coming soon)"),
                ],
                default="clinic",
                max_length=20,
            ),
        ),
    ]
